apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: BASE64_ENCODED_CA_CERTIFICATE
    server: https://x.x.x.x:443
  name: local
contexts:
- context:
    cluster: local
    namespace: dev
    user: fred 
  name: local-dev
current-context: local-dev
kind: Config
preferences: {}
users:
- name: fred 
  user:
    client-certificate-data: BASE64_ENCODED_CLIENT_CERTIFICATE
    client-key-data: BASE64_ENCODED_CLIENT_KEY
